version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306

volumes:
  db-volume:
