version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app